# Generated by Django 5.0.3 on 2024-04-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='bode',
            new_name='body',
        ),
    ]
