# Generated by Django 5.0.3 on 2024-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rename_bode_material_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='material',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
