# Generated by Django 5.0.3 on 2024-04-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='кличка собаки')),
                ('breed', models.CharField(max_length=50, verbose_name='порода')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='фото')),
                ('birthdate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'собаки',
                'ordering': ('name',),
            },
        ),
    ]
