# Generated by Django 5.0.3 on 2024-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='порода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'породы',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthdate',
            field=models.DateTimeField(verbose_name='дата рождения'),
        ),
    ]
